##############################
# Base (Install CPLEX)
FROM python:3.8-slim-buster as base

ARG CPLEX_VERSION=20.10
COPY ILOG_COS_${CPLEX_VERSION}_LINUX_X86_64.bin /tmp/ILOG_COS_${CPLEX_VERSION}_LINUX_X86_64.bin
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends default-jre \
    && /tmp/ILOG_COS_${CPLEX_VERSION}_LINUX_X86_64.bin \
        -i silent \
        -DLICENSE_ACCEPTED=TRUE \
        -DINSTALLER_LOCALE=en

##############################
# Final image

FROM python:3.8-slim-buster
COPY --from=base /opt/ibm /opt/ibm

ARG SIMULATOR_VERSION="1.0.2"

# metadata
LABEL \
    org.opencontainers.image.title="RBApy base" \
    org.opencontainers.image.version="${SIMULATOR_VERSION}" \
    org.opencontainers.image.description="Base Docker image for RBApy" \
    org.opencontainers.image.authors="BioSimulators Team <info@biosimulators.org>" \
    org.opencontainers.image.vendor="BioSimulators Team" \
    \
    base_image="python:3.8-slim-buster" \
    about.summary="Base Docker image for RBApy" \
    maintainer="BioSimulators Team <info@biosimulators.org>"

# Install CPLEX Python API
ARG CPLEX_VERSION_NO_DOT_TRUNC=201
RUN pip install /opt/ibm/ILOG/CPLEX_Studio${CPLEX_VERSION_NO_DOT_TRUNC}/cplex/python/3.8/x86-64_linux/
